// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_base_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_base_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_base_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_base_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_base_2eproto;
class ConfigUpdate;
struct ConfigUpdateDefaultTypeInternal;
extern ConfigUpdateDefaultTypeInternal _ConfigUpdate_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ConfigUpdate* Arena::CreateMaybeMessage<::ConfigUpdate>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ConfigUpdate final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ConfigUpdate) */ {
 public:
  inline ConfigUpdate() : ConfigUpdate(nullptr) {}
  ~ConfigUpdate() override;
  explicit constexpr ConfigUpdate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ConfigUpdate(const ConfigUpdate& from);
  ConfigUpdate(ConfigUpdate&& from) noexcept
    : ConfigUpdate() {
    *this = ::std::move(from);
  }

  inline ConfigUpdate& operator=(const ConfigUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConfigUpdate& operator=(ConfigUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConfigUpdate& default_instance() {
    return *internal_default_instance();
  }
  static inline const ConfigUpdate* internal_default_instance() {
    return reinterpret_cast<const ConfigUpdate*>(
               &_ConfigUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ConfigUpdate& a, ConfigUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(ConfigUpdate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConfigUpdate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConfigUpdate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ConfigUpdate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ConfigUpdate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ConfigUpdate& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConfigUpdate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ConfigUpdate";
  }
  protected:
  explicit ConfigUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUpdateFileFieldNumber = 1,
  };
  // repeated string update_file = 1;
  int update_file_size() const;
  private:
  int _internal_update_file_size() const;
  public:
  void clear_update_file();
  const std::string& update_file(int index) const;
  std::string* mutable_update_file(int index);
  void set_update_file(int index, const std::string& value);
  void set_update_file(int index, std::string&& value);
  void set_update_file(int index, const char* value);
  void set_update_file(int index, const char* value, size_t size);
  std::string* add_update_file();
  void add_update_file(const std::string& value);
  void add_update_file(std::string&& value);
  void add_update_file(const char* value);
  void add_update_file(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& update_file() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_update_file();
  private:
  const std::string& _internal_update_file(int index) const;
  std::string* _internal_add_update_file();
  public:

  // @@protoc_insertion_point(class_scope:ConfigUpdate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> update_file_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_base_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConfigUpdate

// repeated string update_file = 1;
inline int ConfigUpdate::_internal_update_file_size() const {
  return update_file_.size();
}
inline int ConfigUpdate::update_file_size() const {
  return _internal_update_file_size();
}
inline void ConfigUpdate::clear_update_file() {
  update_file_.Clear();
}
inline std::string* ConfigUpdate::add_update_file() {
  std::string* _s = _internal_add_update_file();
  // @@protoc_insertion_point(field_add_mutable:ConfigUpdate.update_file)
  return _s;
}
inline const std::string& ConfigUpdate::_internal_update_file(int index) const {
  return update_file_.Get(index);
}
inline const std::string& ConfigUpdate::update_file(int index) const {
  // @@protoc_insertion_point(field_get:ConfigUpdate.update_file)
  return _internal_update_file(index);
}
inline std::string* ConfigUpdate::mutable_update_file(int index) {
  // @@protoc_insertion_point(field_mutable:ConfigUpdate.update_file)
  return update_file_.Mutable(index);
}
inline void ConfigUpdate::set_update_file(int index, const std::string& value) {
  update_file_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ConfigUpdate.update_file)
}
inline void ConfigUpdate::set_update_file(int index, std::string&& value) {
  update_file_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ConfigUpdate.update_file)
}
inline void ConfigUpdate::set_update_file(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  update_file_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ConfigUpdate.update_file)
}
inline void ConfigUpdate::set_update_file(int index, const char* value, size_t size) {
  update_file_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ConfigUpdate.update_file)
}
inline std::string* ConfigUpdate::_internal_add_update_file() {
  return update_file_.Add();
}
inline void ConfigUpdate::add_update_file(const std::string& value) {
  update_file_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ConfigUpdate.update_file)
}
inline void ConfigUpdate::add_update_file(std::string&& value) {
  update_file_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ConfigUpdate.update_file)
}
inline void ConfigUpdate::add_update_file(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  update_file_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ConfigUpdate.update_file)
}
inline void ConfigUpdate::add_update_file(const char* value, size_t size) {
  update_file_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ConfigUpdate.update_file)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ConfigUpdate::update_file() const {
  // @@protoc_insertion_point(field_list:ConfigUpdate.update_file)
  return update_file_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ConfigUpdate::mutable_update_file() {
  // @@protoc_insertion_point(field_mutable_list:ConfigUpdate.update_file)
  return &update_file_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_base_2eproto
